.\"	$Id$
.\"
.\" Copyright (c) 2016--2017, 2020 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LOWDOWN 1
.Os
.Sh NAME
.Nm lowdown ,
.Nm lowdown-diff
.Nd simple markdown translator
.Sh SYNOPSIS
.Nm lowdown
.Op in_opts
.Op out_opts
.Op Fl s
.Op Fl o Ar file
.Op Fl T Ar mode
.Op Ar file
.Nm lowdown
.Op in_opts
.Op out_opts
.Op Fl o Ar file
.Op Fl T Ar mode
.Fl X Ar keyword
.Op Ar file
.Nm lowdown-diff
.Op in_opts
.Op out_opts
.Op Fl s
.Op Fl o Ar file
.Op Fl T Ar mode
.Ar oldfile
.Op Ar file
.Sh DESCRIPTION
These utilities translate from
.Xr lowdown 5
into a variety of output formats.
.Nm lowdown
formats documents,
.Nm lowdown Fl X Ar keyword
extracts metadata keywords, and
.Nm lowdown-diff
shows differences between documents as formatted output.
The results are written to standard output.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl s
Standalone mode.
This emits a document envelope surrounding the output by drawing from
document metadata.
See
.Sx Metadata
on providing information to the document envelope.
This only applies to
.Fl T Ns Ar html ,
.Fl T Ns Ar ms ,
and
.Fl T Ns Ar man .
.It Fl o Ar file
Send output to
.Ar file
unless it's
.Dq - ,
in which case fall back to the default of standard output.
.It Fl T Ar mode
The output mode.
This may be
.Ar html
for HTML5 output,
.Ar ms
for roff output using the classic (i.e., no-extension)
.Fl ms
package and needing table support,
.Ar term
for ANSI-compatible UTF-8 terminal output, or
.Ar man
for roff output using the classic
.Fl man
package.
A debugging output mode,
.Ar tree ,
shows the parse tree of the input document.
Lastly.
.Ar null
parses the document but does no rendering at all.
.It Fl X Ar keyword
Instead of converting the file, extract the given metadata keyword and
exit.
These will be escaped according to the output mode
.Fl T ;
for example, a title of
.Dq <foo>
in
.Ar html
mode will be extracted as
.Dq &lt;foo&gt; .
In either
.Ar ms
or
.Ar man ,
a title of
.Dq .foo\ebar
will be
.Dq \e&.foo\eebar .
.It Ar oldfile
Input Markdown document used as the basis for comparison with
.Nm lowdown-diff .
.It Ar file
Input Markdown document.
If not given or if
.Ar file
is
.Dq - ,
read from standard input.
.El
.Pp
The following are options for input parsing.
These affect the parse tree passed to all outputs.
.Bl -tag -width Ds
.It Fl -parse-no-autolink
Do not autolink
.Li http ,
.Li https ,
.Li ftp ,
.Li mailto ,
and relative links or link fragments.
.It Fl -parse-no-cmark
Do not tighten input parsing to the CommonMark specification.
This also uses the first ordered list value instead of starting all
lists at one.
In most cases, this is simply less laxist than the original Markdown.
.It Fl -parse-no-fenced
Do not allow for GFM fenced (language-specific) code blocks.
.It Fl -parse-no-footnotes
Do not allow MMD style footnotes.
.It Fl -parse-hilite
Enable highlight span support.
This are disabled by default because it may be erroneously interpreted
as section headers.
.It Fl -parse-math
Recognise mathematics equations.
.It Fl -parse-no-metadata
Do not allow MMD metadata.
For the first paragraph to count as meta-data, the first line must have
a colon in it.
Otherwise it's considered a regular paragraph.
Meta-data is escaped according to the output mode.
.It Fl -parse-no-codeind
Do not parse indented content as code blocks.
.It Fl -parse-no-intraemph
Do not allow emphasis within words and links.
.It Fl -parse-no-strike
Do not allow strikethroughs.
.It Fl -parse-no-super
Do not allow super-scripts.
.It Fl -pasre-notables
Do not allow GFM tables.
.El
.Pp
There are many output options.
The following are shared by all output modes:
.Bl -tag -width Ds
.It Fl -out-standalone
Alias for
.Fl s .
.It Fl -out-no-smarty
Do not use the smart typography filter.
By default, certain character sequences are translated into
output-specific glyphs.
.El
.Pp
What follows are per-output options.
For HTML with
.Fl T Ns Ar html ,
these are as follows:
.Bl -tag -width Ds
.It Fl -html-no-skiphtml
Output embedded HTML.
By default, embedded HTML is not output at all.
See
.Fl -html-no-escapehtml .
.It Fl -html-no-head-ids
Do not output
.Li id
attributes for headers.
.It Fl -html-no-escapehtml
If
.Fl -html-no-skiphtml
has been specified, this causes embedded HTML not to be escaped, and is
instead output verbatim.
This has no effect if
.Fl -html-no-skiphtml
has not been specified.
.It Fl -html-hardwrap
Hard-wrap paragraph content by outputting line breaks where applicable.
.El
.Pp
For both
.Fl T Ns Ar man
and
.Fl T Ns Ar ms ,
the following apply:
.Bl -tag -width Ds
.It Fl -nroff-hard-wrap
Hard-wrap paragraph content by outputting line breaks where applicable.
.It Fl -nroff-no-skiphtml
Output embedded HTML.
This usually doesn't make sense because the HTML won't be interpreted by
the output reader.
By default, HTML is omitted.
.It Fl -nroff-no-numbered
If
.Fl -nroff-no-groff
is set, don't output numbered headings.
Only applies to
.Fl T Ns Ar ms .
.It Fl -nroff-no-groff
Don't use
.Xr groff 1
style section headings and don't output PDF hyper-links.
See
.Fl -nroff-no-numbered .
Only applies to
.Fl T Ns Ar ms .
.El
.Pp
Only
.Fl T Ns Ar html
includes graphics and equations in output.
All other outputs omit these statements.
.Ss Metadata
If not disabled with
.Fl -parse-no-metadata ,
the following metadata keys are used when in standalone
.Pq Fl s
mode:
.Bl -tag -width Ds
.It Li copyright
A document copyright (without the word
.Dq Copyright ) ,
for example,
.Dq 2017, Kristaps Dzonsons .
This is currently only used in the
.Fl T Ar ms
output mode.
.It Li date
Document date in ISO-8601 YYYY-MM-DD or YYYY/MM/DD format.
Overriden by
.Li rcsdate .
Defaults to current date.
Used in all output modes.
.It Li rcsdate
Document date in RCS date format.
Overrides
.Li date .
Defaults to current date.
Used in all output modes.
.It Li title
Document title, defaulting to
.Dq Untitled article .
Used in all output modes.
.It Li affiliation
Author affiliation (organisation or institution).
Multiple affiliations may be separated by more than one space (including
newlines).
Used in all output modes.
.It Li author
Document author.
Multiple authors may be separated by more than one space (including
newlines).
Overrides
.Li rcsauthor .
Used in all output modes.
.It Li rcsauthor
Document author in RCS author format.
Overriden by
.Li author .
Used in all output modes.
.It Li css
A CSS file included in the HTML5 document head.
Multiple CSS files (in order) may be separated by more than one space
(including newlines).
Only used in
.Fl T Ar html
mode.
.It Li javascript
A JavaScript file included in the HTML5 document head.
Multiple script files (in order) may be separated by more than one space
(including newlines).
Only used in
.Fl T Ar html
mode.
.El
.Ss Diffing
If invoked as
.Nm lowdown-diff ,
the traditional Markdown output is augmented with features for viewing
file differences.
These depend upon the output mode.
.Bl -tag -width Ds
.It Fl T Ns Ar term
Removed and inserted data have different background colours.
.It Fl T Ns Ar html
When data has been removed from the old document, it is marked up with the
.Li <del>
element.
When data has been inserted into the new document,
.Li <ins>
is used instead.
.It Fl T Ns Ar man , Fl T Ns Ar ms
When data has been removed, it is coloured red.
When data has been inserted, it is coloured in green.
In either case, your formatter must support colours or the texts will be
freely intermingled.
.El
The algorithm used for diffing derives from
.Dq Detecting Changes in XML Documents
.Pq 2002 .
The algorithm for computing the shortest edit script between text nodes is
.Dq An O(NP) sequence comparison algorithm
.Pq 1990 .
.Sh EXIT STATUS
.Ex -std lowdown lowdown-diff
.Pp
If the
.Fl X
flag is used,
.Nm lowdown
exits with an error if the given keyword is not found.
.Sh EXAMPLES
To view a Markdown file on an ANSI-compatible, UTF-8 terminal:
.Pp
.Dl lowdown -Tterm foo.md | less -r
.Pp
To emit a standalone HTML5 document from a file
.Pa foo.md :
.Pp
.Dl lowdown -s foo.md > foo.html
.Pp
To do the same but using
.Xr groff 1
to format as a PS file:
.Bd -literal -offset indent
lowdown -s -Tms foo.md | \e
  groff -t -mspdf -k -Kutf8 > foo.ps
.Ed
.Pp
The arguments to
.Xr groff 1
dictate input type
.Pq Fl m Ns Ar spdf ,
input encoding
.Pq Fl k , Fl K Ns Ar utf8 ,
and extensions
.Pq Fl t .
Note that
.Fl m Ns Ar spdf
is used instead of
.Fl m Ns Ar s
and
.Fl m Ns Ar pdfmark
to allow for the
.Dq XN
macro, which generates a table of contents for the output PS or PDF.
This macro is otherwise ignored.
.Pp
Alternatively, using only
.Xr mandoc 1 :
.Bd -literal -offset indent
lowdown -sTman foo.md | mandoc -Tps > foo.ps
.Ed
.Pp
To have PDF output, use the
.Xr pdfroff 1
utility instead of the
.Fl T Ns Ar pdf
output to
.Xr groff 1 ,
as it manages image conversion.
The
.Fl i
flag notes standard input; other flags are passed to
.Xr groff 1 .
.Bd -literal -offset indent
lowdown -sTms foo.md | \e
  pdfroff -i -t -mspdf -k -Kutf8 > foo.pdf
.Ed
.Pp
To extract the HTML-escaped title from a file's metadata:
.Pp
.Dl lowdown -X title foo.md
.Pp
Lastly, using a traditional
.Xr troff 1 ,
use the following:
.Bd -literal -offset indent
lowdown -Dnroff-groff -sTms foo.md | \e
  tbl | troff -Tps -ms -mpdfmark > foo.ps
.Ed
.Sh SEE ALSO
.Xr lowdown 3 ,
.Xr lowdown 5
.Rs
.%A Gregory Cobena
.%A Serge Abiteboul
.%A Amelie Marian
.%D 2002
.%T Detecting Changes in XML Documents
.%U https://www.cs.rutgers.edu/~amelie/papers/2002/diff.pdf
.Re
.Rs
.%A Wu Sun
.%A Manber Udi
.%A Myers Gene
.%T An O(NP) sequence comparison algorithm
.%J Information Processing Letters
.%V Volume 35
.%I Issue 6
.%D 1990
.Re
.Sh STANDARDS
.Nm lowdown
and
.Nm lowdown-diff
implement the classic Markdown specification along with some
extensions.
See
.Sx Input features
and
.Sx Output features
for a list.
.Sh AUTHORS
The
.Nm lowdown
and
.Nm lowdown-diff
utilities were forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from
.Lk https://github.com/hoedown/hoedown hoedown .
