.\"	$Id$
.\"
.\" Copyright (c) 2020 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LOWDOWN_LATEX_RNDR 3
.Os
.Sh NAME
.Nm lowdown_latex_rndr
.Nd render Markdown into LaTeX
.Sh LIBRARY
.Lb liblowdown
.Sh SYNOPSIS
.In sys/queue.h
.In stdio.h
.In lowdown.h
.Ft void
.Fo lowdown_latex_rndr
.Fa "hbuf *out"
.Fa "struct lowdown_metaq *mq"
.Fa "void *arg"
.Fa "const struct lowdown_node *n"
.Fc
.Sh DESCRIPTION
Renders a node tree
.Fa n
created by
.Xr lowdown_doc_parse 3
or
.Xr lowdown_doc_diff 3
using the LaTeX renderer
.Fa arg
as returned by
.Xr lowdown_latex_new 3 .
The output is written into
.Fa out ,
which must be initialised and freed by the caller.
.Pp
If
.Fa mq
is not
.Dv NULL ,
it is filled with any metadata as parsed.
It must be initialised and its contents freed with
.Xr lowdown_metaq_free 3 .
.Sh EXAMPLES
The following assumes the the string
.Va buf
of length
.Va bsz
consists of Markdown content.
.Bd -literal -offset indent
hbuf *out;
hdoc *doc;
void *rndr;
struct lowdown_node *n;

if ((doc = lowdown_doc_new(NULL)) == NULL)
	err(1, NULL);
if ((n = lowdown_doc_parse(doc, NULL, buf, bsz)) == NULL)
	err(1, NULL);
lowdown_doc_free(doc);

if ((out = hbuf_new(256)) == NULL)
	err(1, NULL);
if ((rndr = lowdown_latex_new(NULL)) == NULL)
	err(1, NULL);
lowdown_latex_rndr(out, NULL, rndr, n);
lowdown_latex_free(rndr);
lowdown_node_free(n);

fwrite(out->data, 1, out->size, stdout);
free(out->data);
.Ed
.Sh SEE ALSO
.Xr lowdown 3 ,
.Xr lowdown_latex_free 3 ,
.Xr lowdown_latex_new 3
