.NH 1
a\c
.pdfhref L -D footnote-1 -- \**
.pdfhref L -D footnote-2 -- \**
.pdfhref L -D footnote-3 -- \**
.pdfhref O 1 a
.pdfhref M a
.FS
.pdfhref M footnote-1
Klingon insult, meaning something like \(lqweirdo,\(rq deriving from
the verb[\(hapt4] \(lqto be weird\(rq (\fBtaQ\fR), with and [sic] you (plural)
imperative prefix (\fBpe-\fR).
.FE
.FS
.pdfhref M footnote-2
asdfadfasfd
.FE
.FS
.pdfhref M footnote-3
!!(U!)(!!
.FE
.LP
now here
