.PP
.pdfhref W -D http://www.google.com/search?q=%E2%99%A5 -- text
.pdfhref W -D http://www.google.com/search?q=%E2%80%A6 -- text
.pdfhref W -D http://www.google.com/search?q=hi%22there -- text
.pdfhref W -D http://www.google.com/search?q=hi%20there -- text
.pdfhref W -D http://www.google.com/search?q=hi%5Ethere -- text
.pdfhref W -D http://www.google.com/search?q=hi&there -- text
.pdfhref W -D http://www.google.com/search?q=hi%0Dthere -- text
.PP
.pdfhref W -D http://www.google.com/search?q=%E2%99%A5 -- http://www.google.com/search?q=%E2%99%A5
or
.pdfhref W -D http://www.google.com/search?q=%E2%80%A6 -- http://www.google.com/search?q=%E2%80%A6
or
