.Sh NAME
.Nm foo 
.Nd xyzzy
.Sh SYNOPSIS
.Nm apropos
.Oo
.Fl afk Ns
.Oc
.Oo
.Fl C
.Ar file Ns
.Oc
.Oo
.Fl M
.Ar path Ns
.Oc
.Oo
.Fl m
.Ar path Ns
.Oc
.Oo
.Fl O
.Ar outkey Ns
.Oc
.Oo
.Fl S
.Ar arch Ns
.Oc
.Oo
.Fl s
.Ar section Ns
.Oc
.Ar expression
.Ar ...
.Nm addr2line
.Oo
.Fl a| Ns
.Fl -addresses Ns
.Oc
.Oo
.Fl b
.Ar bfdname| Ns
.Fl -target Ns
.Ar =bfdname Ns
.Oc
.Oo
.Fl C| Ns
.Fl -demangle Ns
.Oo
.Ar =style Ns
.Oc Ns
.Oc
.Oo
.Fl e
.Ar filename| Ns
.Fl -exe Ns
.Ar =filename Ns
.Oc
.Oo
.Fl f| Ns
.Fl -functions Ns
.Oc
.Oo
.Fl s| Ns
.Fl -basename Ns
.Oc
.Oo
.Fl i| Ns
.Fl -inlines Ns
.Oc
.Oo
.Fl j| Ns
.Fl -section Ns
.Ar =name Ns
.Oc
.Oo
.Fl H| Ns
.Fl -help Ns
.Oc
.Oo
.Fl V| Ns
.Fl -version Ns
.Oc
.Oo
.Ar addr
.Ar addr
.Ar ... Ns
.Oc
.Sh DESCRIPTION
Hi there.
