.Dd $Mdocdate$
.Dt LOWDOWN 5
.Os
.
.
.Sh NAME
.Nm lowdown
.Nd Markdown reference for lowdown
.
.
.Sh DESCRIPTION
Markdown is an easy-to-read, easy-to-write plain text formatting syntax.
A document written using Markdown is essentially meant to be generated
as-is, containing as little formatting and mark-up as possible.
Markdown was intended as a writing format for the web, only, but serves
as a quick and easy writing tool to generate documents that require
minimal stylistic formatting.
.
.
.Sh BLOCK ELEMENTS
A block element starts on a new line and takes up the full-width (left
and right) of the page available.
A block element can contain a span element.
.
.Ss Paragraphs and Line Breaks
A paragraph is made up of one or more lines of text, and paragraphs are
separated by blank lines.
To insert a hard line break: insert two spaces at the end of the line.
.
.Ss Headers
Markdown supports two styles of headers: Setext ("underlined") and
atx ("hash-marked").
For Setext headers, underline the given word using equal (=) signs for
first-level headers and dashes (-) for second-level headers.
.Bd -literal -offset indent
This is a setext Header 1
========================
.Ed
.Pp
For axt headers, use the corresponding number of hash characters to the
corresponding level of header, up to 6 levels, at the start of the line
separated by one space followed by the header.
.Bd -literal -offset indent
## This is an atx Header 2
.Ed
.
.Ss Block Quotes
Markdown supports block quoting by invoking a single right-angle bracket
(>) indented by either four spaces or one tab, followed by a space at
the start of each line.
.Bd -literal -offset indent
> The Prime Directive is not just a set of rules; it is a philosophy...
> and a very correct one.
>
> History has proven again and again that whenever mankind interferes
> with a less developed civilization... the results are invariably
> disastrous.
.Ed
.Pp
Markdown also allows you to be lazy with block quotes: you can choose to
only invoke the right-angle bracket at the start of paragraph and omit
it entirely between paragraphs.
.Bd -literal -offset indent
> It is possible to commit no mistakes and still lose.

> The road from legitimate suspicion to rampant paranoia is much shorter
than we think.
.Ed
.Pp
Markdown supports nested block quotes as well as other Markdown elements
within block quotes, such as headers, ordered/unordered lists, and code
blocks.
.Bd -literal -offset indent
> ### atx header 3
>
> > I'd be delighted to offer any advice I have on understanding women.
> > When I have
> > some, I'll let you know.
>
> 1.  advice list item 1
> 2.  advice list item 2
> 3.  advice list item 3
>
> Here’s the code to implement advice JLP’s advice:
> 	return shell_exec("echo $input | $womenadvice_script")
.Ed
.
.Ss Lists
Markdown supports both ordered and unordered lists.
Ordered lists are invoked as numbers followed by periods (1.) and
rendered in the same format.
Note: it does not matter which order or
which numbers you use in your ordered lists, Markdown will generate an
ordinal list from your input as long as you start your list with (1.).
.Bd -literal -offset indent
1. Make.
2. It.
1. So. (Not 1. again!)
.Ed
.Pp
Unordered lists, on the other hand, can be invoked using either
asterisks (*), pluses (+), and hyphens (-), and can be a mix of all
three, but are rendered as bullet points.
.Bd -literal -offset indent
- Earl Grey tea.
∗ Shakespeare.
+ Exotic fish.
.Ed
.Pp
To insert paragraphs into a list item, indent each paragraph with either
four spaces or one tab.
.Bd -literal -offset indent
- First list item

	Courage can be an emotion too.

	No being is so important that he can usurp the rights of another.
+ Second list item
+ Third list item
.Ed
.Pp
To insert block quotes into a list item, indent the block quote with
four spaces of one tab.
Code blocks need to be indented twice to be inserted into a listen item
– either with eight spaces or two tabs.
.Bd -literal -offset indent
∗ List item 1
∗ List item 2

	> Winds shall rise
	> and fog descend
	> So leave here all
	> or meet your end

∗ That was “very bad poetry, Captain”
∗ Here is an indented code block
	<alias path='echo -e ${PATH//:/\\n}'>
.Ed
.
.Ss Code Blocks
Markdown supports source code text through pre-formatted code blocks.
Each code block contains opaque/literal text.
This means that new lines and white spaces are retained – they’re not
formatted in any way, and any text inside the code block is not
interpreted.
To invoke a code block, indent each line with 4 spaces or 1 tab.
.Bd -literal -offset indent
Here is a paragraph about Bridge protocol

	Here is a code block for the command "Engage"
.Ed
.Pp
Within a code block, text is escaped given the output format.
Therefore, characters that would normally need to be escaped in other
text processing languages such as ampersands (&) do not need to be
escaped.
.Bd -literal -offset indent
Here is how you start the program xterm:

	xterm &
.Ed
.
.Ss Horizontal Rules
A horizontal rule is a line that goes across a web page.
Markdown supports horizontal rules by invoking three or more asterisks
(*), hyphens (-), or underscores (_), on their own line.
Markdown disregards whether or not there are spaces between these
characters.
.Bd -literal -offset indent
**
* *
---
- - -
___
_ _ _
_______________________________________________________________
.Ed
.
.
.Sh SPAN ELEMENTS
A span element does not have to start on a new line and only takes up as
much width as necessary.
A span element cannot contain a block element.
.
.Ss Emphasis
Markdown supports different styles of emphasis, where strong is usually
rendered as bold and emphasis is usually rendered as italics.
Text surrounded by a single asterisk (*) or underscore (_) will be
rendered as italic.
.Bd -literal -offset indent
*Captain Picard*
_Captain Picard_
.Ed
.Pp
Text surrounded by a double asterisk (**) or underscore (__) will be
rendered as bold.
.Bd -literal -offset indent
**Jean-Luc Picard**
__Jean-Luc Picard__
.Ed
.Pp
Markdown supports emphasis within the middle of a word:
.Bd -literal -offset indent
En**ter*prise
.Ed
.Pp
In order to produce a literal asterisks (*) or underscore (_) simply
surround the character by white space.
.Bd -literal -offset indent
* USS Enterprise * will not be emphasized
.Ed
.
.Ss Links
Markdown supports two types of links: inline and reference.
In both cases, the linked text is denoted by [square brackets].
n inline link uses parentheses containing the URL immediately following
the linked text in square brackets to invoke the link.
.Bd -literal -offset indent
[text to link](http://click.here.to.go.to.link.com)
.Ed
.Pp
For local referencing on the same server, Markdown supports relative
paths:
.Bd -literal -offset indent
[Picard](/Picard/)
.Ed
.Pp
A reference link on the other hand, keeps the URL outside of the text,
usually in the footnotes, and has the benefit of making the text more
readable.
Invoke a reference link by defining it using with a title
[square brackets] followed a colon followed by its corresponding URL or
path to image:
.Bd -literal -offset indent
[link1]: http://url.to.see.cool.captain.picard.quotes
.Ed
.Pp
then reference it anywhere in your text using [text to the link] and the
same [link title], both in [square brackets] next to each other:
.Bd -literal -offset indent
here is some text about Captain Jean Luc Picard [text to link][link1].
.Ed
.
.Ss Automatic Links
Automatic links are links to URLs or emails that do not require text to
links, rather they show the full link or email address that works
simultaneously as the clickable link.
To invoke an automatic link, surround the link or email address with
angle brackets < >
.Bd -literal -offset indent
<http://captainmarkdownpicard.com/>

<markdown@captainpicard.com>
.Ed
.
.Ss Images
Markdown uses a plain text image syntax that very much resembles the
links syntax.
The key difference is that images require an exclamation
mark (!) before the text to link surrounded by square brackets [ ].
.Bd -literal -offset indent
![Image text]
.Ed
.Pp
Just like with links, Markdown also supports inline and reference
images.
Markdown invokes inline style images by an exclamation mark (!) followed
by the optional text for the image (also known as the caption)
surrounded by square brackets [ ] followed by the URL or the path to
image surrounded by parentheses ( ).
.Bd -literal -offset indent
![Picture of Picard](http://picard.pictures.for.markdown.net)
.Ed
.Pp
Markdown invokes reference style images by defining the image reference
in your footnote or endnote using an image ID surrounded by square
brackets [ ] followed by a colon followed by an image URL or path to
image and optional title attribute in quotation marks “ ”.
.Bd -literal -offset -indent
[image1]: http://picard.pictures.for.markdown.net “Picture of Picard”
.Ed
.Pp
Invoking the image reference in your text document will look like this
.Bd -literal -offset indent
Here is some text about Captain Picard. Now I want to include a picture:
![Captain Picard][image1]
.Ed
.
.Ss Code
In addition to code blocks, Markdown also supports inline code (within
paragraphs).
To invoke a span of code, surround the code using backtick quotes (`).
.Bd -literal -offset indent
I need your IP address to send you Picard pix. Use the `ifconfig
en(0)`command.
.Ed
.Pp
Markdown supports literal backticks (`) within a code of span.
Surround the code using multiple backticks (``) if you want the
backticks within the span of code to show up as literal characters.
.Bd -literal -offset indent
``Here is a span of code with `back ticks` inside it.``
.Ed
.Pp
If you have a literal backtick at the start or end of the span of code,
leave a space between the literal backtick and the delimiting backticks.
.Bd -literal -offset indent
```So many backticks```
.Ed
.
.
.Sh Miscellaneous
.
.Ss Automatic Escapes
When writing for the web, there are two special characters that normally
demand escaping: angle brackets (<) and ampersands (&).
Markdown supports automatic escapes where these characters do not need
to be escaped and can be used literally.
.Bd -literal -offset indent
Kirk < Picard

Picard & Riker = great team.
.Ed
.
.Ss Backslash Escapes
Markdown supports backslash escapes to render literal characters that
would otherwise invoke a particular Markdown element.
Surrounding a phrase with single asterisks renders it as italic.
.Bd -literal -offset indent
*Captain Picard*
.Ed
.Pp
However, if you want to invoke those italics as literal characters,
Markdown allows you to escape those asterisks using backslashes.
.Bd -literal -offset indent
\e*Captain Picard\e*
.Ed
.Pp
Markdown supports backslash escapes for the following characters:
.Pp
.Bl -tag -width Ds -compact
.It Li *
asterisk
.It Li \e
backslash
.It Li `
backtick
.It Li {
curly brace
.It Li \&!
exclamation mark
.It Li #
hash mark
.It Li -
minus sign
.It Li \&(
parentheses
.It Li \&.
period
.It Li +
plus sign
.It Li \&[
square brackets
.It Li _
underscore
.El
.
.
.Sh SEE ALSO
.Xr lowdown 1
.Sh STANDARDS
Which version of markdown.
.Sh AUTHORS
The
.Nm
reference was written by
.An Christina Sophonpanich ,
.Mt huck@divelog.blue .
