.\"	$Id$
.\"
.\" Copyright (c) 2016 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 22 2016 $
.Dt LOWDOWN 1
.Os
.Sh NAME
.Nm lowdown
.Nd simple markdown translator
.Sh SYNOPSIS
.Nm lowdown
.Op Fl s
.Op Fl o Ar file
.Op Fl t title
.Op Fl T mode
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility translates from markdown into HTML5 in XML mode (the default) or
roff using the
.Fl ms
macro package.
If not given a
.Ar file ,
or if
.Ar file
is
.Dq - ,
.Nm
reads from standard input.
The results are written to standard output.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl s
Standalone mode.
This emits a minimal HTML5 or roff document surrounding the output.
You will probably need to hand-edit it.
You probably want to use
.Fl t
as well.
.It Fl o Ar file
Send output to
.Ar file
unless it's
.Dq - ,
in which case fall back to the default of standard output.
.It Fl t Ar title
If used with
.Fl s ,
this specifies the page title.
The title is used in the
.Li <title>
tags, if in HTML5 mode, or
.Li .Tl
in roff mode.
.It Fl T Ar mode
The output mode.
This may be
.Ar html
for HTML5 output ,
.Ar nroff
for roff output using the classic (i.e., no-extension)
.Fl ms
package and needing table support, or
.Ar man
for roff ouput using the classical
.Fl man
package.
.El
.Pp
For best results, use the
.Fl T Ar html
output, as it includes graphics and equations.
The
.Ar nroff
and
.Ar man
modes will elide graphics and equations.
.Sh EXAMPLE
To emit a standalone HTML5 document from a file
.Pa foo.md :
.Pp
.Dl lowdown -s foo.md > foo.html
.Pp
To do the same but using
.Xr groff 1
to format as a PS file:
.Pp
.Dl lowdown -s -T nroff foo.md | groff -t -ms > foo.ps
.Pp
Alternatively, using only
.Xr mandoc 1 :
.Pp
.Dl lowdown -s -T man foo.md | mandoc -Tps > foo.ps
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
Not exactly a standard, but
.Nm
implements the
.Lk Markdown http://daringfireball.net/projects/markdown/syntax
specification.
It deviates from the specification in stripping inline HTML and that the
first paragraph is contained within an <aside> element.
It augments the specification in adding support for autolinking, fenced
code, tables, footnotes, disabled inline HTML, and
.Dq smartypants .
.Sh AUTHORS
The
.Nm
utility was forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from
.Lk https://github.com/hoedown/hoedown hoedown .
