.\"	$Id$
.\"
.\" Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LOWDOWN 3
.Os
.Sh NAME
.Nm lowdown ,
.Nm lowdown_buf ,
.Nm lowdown_errstr ,
.Nm lowdown_file
.Nd simple markdown translator library
.Sh LIBRARY
.Lb liblowdown
.Sh SYNOPSIS
.In stdio.h
.In lowdown.h
.Ft void
.Fo lowdown_buf
.Fa "const struct lowdown_opts *opts"
.Fa "const unsigned char *buf"
.Fa "size_t bufsz"
.Fa "unsigned char **ret"
.Fa "size_t *retsz"
.Fc
.Ft "const char *"
.Fo lowdown_errstr
.Fa "enum lowdown_err"
.Fc
.Ft int
.Fo lowdown_file
.Fa "const struct lowdown_opts *opts"
.Fa "FILE *f"
.Fa "unsigned char **ret"
.Fa "size_t *retsz"
.Fc
.Sh DESCRIPTION
The
.Nm lowdown
library parses Markdown into HTML or roff
.Pq Fl ms No or Fl man No macro sets .
See
.Xr lowdown 1
for a list of supported Markdown features.
.Pp
There are two forms of invocation.
The first,
.Nm lowdown_file ,
operates from an already-opened
.Vt FILE
stream.
The results are stored in
.Fa ret ,
which must later be passed to
.Xr free 3 ,
of size
.Fa retsz .
.Pp
The second,
.Nm lowdown_buf ,
operates directly on an input buffer
.Fa buf
of size
.Fa bufsz .
.Pp
Both accept a configuration structure,
.Fa opts ,
which has the following fields:
.Bl -tag -width Ds
.It Va arg
Pointer passed to
.Va msg ,
if not
.Dv NULL .
.It Va feat
Features used during the parse.
This bit-field may have the following bits OR'd:
.Pp
.Bl -tag -width Ds -compact
.It Dv LOWDOWN_TABLES
Allow for GFM tables.
.It Dv LOWDOWN_FENCED
Allow for GFM fenced (language-specific) code blocks.
.It Dv LOWDOWN_FOOTNOTES
MMD style footnotes.
This only supports one-liner footnotes on the same line as the footnote
definition (not the in-line referent).
.It Dv LOWDOWN_AUTOLINK
Autolink
.Li http ,
.Li https ,
.Li ftp ,
.Li mailto ,
and relative links or link fragments.
.It Dv LOWDOWN_STRIKE
Strikethrough support.
.It Dv LOWDOWN_UNDER
Underline instead of emphasise.
.It Dv LOWDOWN_HILITE
Highlight.
Do not use this option.
.It Dv LOWDOWN_QUOTE
Recognise quotes.
You probably don't want this.
.It Dv LOWDOWN_SUPER
Allow for super-scripts.
This accepts foo^bar, which puts the parts following the caret until
whitespace in superscripts; or foo^(bar), which puts only the parts in
parenthesis.
.It Dv LOWDOWN_MATH
Recognise single-dollar math mode.
.It Dv LOWDOWN_NOINTEM
Disable emphasis with links.
.It Dv LOWDOWN_SPHD
Require a space between hash marks and header.
.It Dv LOWDOWN_MATHEXP
Recognise double-dollar math mode.
This only works if
.Dv LOWDOWN_MATH
has also been set.
.It Dv LOWDOWN_NOCODEIND
Do not indent code blocks.
.El
.Pp
If set to zero, or if the structure is not specified, the defaults are
.Dv LOWDOWN_FOOTNOTES |
.Dv LOWDOWN_AUTOLINK |
.Dv LOWDOWN_TABLES |
.Dv LOWDOWN_SUPER |
.Dv LOWDOWN_STRIKE |
.Dv LOWDOWN_FENCED .
.It Va msg
Message function for logging messages.
If
.Dv NULL ,
messages are not logged.
.It Va type
May be set to
.Dv LOWDOWN_HTML
for HTML5 output,
.Dv LOWDOWN_MAN
for
.Fl man
macros, or
.Dv LOWDOWN_NROFF
for
.Fl ms
macros.
.El
.Pp
The
.Nm lowdown_errstr
is provided to return a human-readable version of
.Vt "enum lowdown_err" .
It returns a generic (en_GB) description.
.Sh RETURN VALUES
The
.Nm lowdown_file
returns zero if the file-reading sequenced failed, non-zero otherwise.
.Sh SEE ALSO
.Xr lowdown 1
.Sh AUTHORS
The
.Nm
library was forked by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv
from
.Lk https://github.com/hoedown/hoedown hoedown .
