.\"	$Id$
.\"
.\" Copyright (c) 2016 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 8 2016 $
.Dt LOWDOWN 1
.Os
.Sh NAME
.Nm lowdown
.Nd simple markdown translator
.Sh SYNOPSIS
.Nm lowdown
.Op Fl s
.Op Fl o Ar file
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility translates from markdown into HTML5 in XML mode.
Specifically, it outputs the translated page contents without leading
HTML context or document type declaration.
If not given a
.Ar file ,
or if
.Ar file
is
.Dq - ,
.Nm
reads from standard input.
The results are written to standard output.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl s
Standalone mode.
This emits a minimal HTML5 document surrounding the output.
You will probably need to hand-edit it.
.It Fl o Ar file
Send output to
.Ar file
unless it's
.Dq - ,
in which case fall back to the default of standard output.
.El
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
Not exactly a standard, but
.Nm
implements the
.Lk Markdown http://daringfireball.net/projects/markdown/syntax
specification.
It deviates from the specification in stripping inline HTML and that the
first paragraph is contained within an <aside> element.
It augments the specification in adding support for autolinking, fenced
code, tables, footnotes, and
.Dq smartypants .
.Sh AUTHORS
The
.Nm
utility was forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from
.Lk https://github.com/hoedown/hoedown hoedown .
