.Sh NAME
.Nm foo
.Nd xyzzy
.Sh SYNOPSIS
.Nm apropos
.Op Fl afk
.Op Fl C Ar file
.Op Fl M Ar path
.Op Fl m Ar path
.Op Fl O Ar outkey
.Op Fl S Ar arch
.Op Fl s Ar section
.Ar expression
.Ar ...
.Nm addr2line
.Op Fl a Ns | Ns Fl \-addresses
.Op Fl b Ar bfdname Ns | Ns Fl \-target Ns = Ns Ar bfdname
.Op Fl C Ns | Ns Fl \-demangle Ns Oo Ar =style Oc
.Op Fl e Ar filename Ns | Ns Fl \-exe Ns = Ns Ar filename
.Op Fl f Ns | Ns Fl \-functions
.Op Fl s Ns | Ns Fl \-basename
.Op Fl i Ns | Ns Fl \-inlines
.Op Fl j Ns | Ns Fl \-section Ns = Ns Ar name
.Op Fl H Ns | Ns Fl \-help
.Op Fl V Ns | Ns Fl \-version
.Op Ar addr Ar addr Ar ...
.Sh DESCRIPTION
Hi there.
