name: Regression Tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bmake valgrind
    - name: Configure
      run: |
        ./configure
        echo 'CFLAGS += -fsanitize=undefined,address -fomit-frame-pointer -O0' > Makefile.local
        echo 'LDFLAGS += -fsanitize=undefined,address -fomit-frame-pointer -O0' >> Makefile.local
        bmake regress
        rm -f Makefile.local
        bmake clean
        bmake valgrind
