name: Regression Tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y bmake valgrind
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure
        echo 'CFLAGS += -fsanitize=undefined -fsanitize=address' > Makefile.local
        echo 'LDFLAGS += -fsanitize=undefined -fsanitize=address' >> Makefile.local
        bmake regress
        rm -f Makefile.local
        bmake clean
        bmake valgrind
